#!/bin/python3

import json
import pygame
import platform
import getpass
import subprocess

ARCH = platform.machine()
OS = platform.system()
EXE_NAME = f"{ARCH}-{OS}-Infinity.exe"

screen = pygame.display.set_mode((275, 150))
clock = pygame.time.Clock()


def error(message):
    font = pygame.font.SysFont('Arial', 16)

    text = font.render(message, True, (0, 0, 0))

    display_msg = True

    while display_msg:
        pygame.display.flip()

        for event in pygame.event.get():
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE or pygame.QUIT:
                    display_msg = False

        screen.fill((255, 255, 255))
        clock.tick(60)

        screen.blit(text, (10, 15))


def check_files():
    try:
        open(f"/home/{getpass.getuser()}/.infinity/{EXE_NAME}", "r")
    except:
        error("Can't find game file, reinstall Infinity")

    try:
        open(f"/home/{getpass.getuser()}/.infinity/infinity.json")
    except:
        error("Can't find game info file")


def read_info():
    info_file = open(f"/home/{getpass.getuser()}/.infinity/infinity.json")

    info = json.load(info_file)

    if info['version'] == "0":
        error("Version field in info file is invalid")


def main():
    print("Loading Infinity...")
    pygame.font.init()
    pygame.display.set_caption(f'Loading {EXE_NAME}...')

    check_files()
    read_info()

    subprocess.call([f"/home/{getpass.getuser()}/.infinity/{EXE_NAME}"])


if __name__ == '__main__':
    main()
