#!/bin/python3

import bs4
import json
import pygame
import platform
import getpass
import subprocess
import urllib
import urllib.request

ARCH = platform.machine()
OS = platform.system()
EXE_NAME = f"{ARCH}-{OS}-Infinity.exe"

screen = pygame.display.set_mode((500, 180))
clock = pygame.time.Clock()


def error(message):
    font = pygame.font.SysFont('Arial', 15)

    text = font.render(message, True, (0, 0, 0))

    display_msg = True

    while display_msg:
        pygame.display.flip()

        for event in pygame.event.get():
            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE or pygame.QUIT:
                    display_msg = False

        screen.fill((255, 255, 255))
        clock.tick(60)

        screen.blit(text, (6, 15))


def check_files():
    try:
        open(f"/home/{getpass.getuser()}/.infinity/{EXE_NAME}", "r")
    except:
        error("Can't find game file, reinstall Infinity")

    try:
        open(f"/home/{getpass.getuser()}/.infinity/infinity.json")
    except:
        error("Can't find game info file")


def read_info():
    info_file = open(f"/home/{getpass.getuser()}/.infinity/infinity.json")

    info = json.load(info_file)

    soup = bs4.BeautifulSoup(urllib.request.urlopen("https://NathanMcMillan54.github.io/games/infinity_info.html").read(), "html.parser")

    version = soup.find("div", {"class": "version"}).string
    date = soup.find("div", {"class": "release_date"}).string

    if str(info['version']) != str(version):
        error(f"Your game ({info['version']}) needs to be updated (to {version})")
    elif str(info['date']) != str(date):
        error("Your game is outdated and needs to be updated")


def main():
    print("Loading Infinity...")
    pygame.font.init()
    pygame.display.set_caption(f'Loading {EXE_NAME}...')

    check_files()
    read_info()

    subprocess.call([f"/home/{getpass.getuser()}/.infinity/{EXE_NAME}"])


if __name__ == '__main__':
    main()
